### PR TITLE
Stage-react-api

### PR DESCRIPTION
**Pull request by moorek11c**
Note: This project nolonger uses the JSON dependency it uses mock data from a file within the project.

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello! Good job on your diploma project! It looks very decent already, but will require some fixes. Please find comments in the list below, I hope those issues will be easy to fix!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Links in footer have default styles: https://prnt.sc/CQtkjNDUkDjl

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Home page scrolls on all resolutions 321- 1456px

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* "Registration successful" popup can't be displayed.
* Please add come sample saved cards on saved-news page so that I can test the layout.

- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/BLuGjF3u8Iku Elements can't be used without their block. There are many similar cases in the project, please correct all of them

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* `news__card` `<li>` can't be used as child of `<div>`
* news cards list should be a list `<ul>`, or/and the card needs to be `<article>`
* Links in `header` and `footer` should be in nav, ul or ul inside nav.

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* `news__card` `<li>` can't be used as child of `<div>`
* https://prnt.sc/csEfxx-31fUM

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover effect on a card bookmark from the mockup: https://prnt.sc/o7v7VfcnRLh8
* Hover effect on trash can icon from the mockup: https://prnt.sc/KFTCWRfN-fBQ
* The bookmark on the card should have "marked" state implemented: https://prnt.sc/hvF3kmwz4XPe

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 46

**Comment by ImaliaNsk** [comment]
Good job with corrections! The project looks better, but still has some issues to work on.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Home page scrolls on 320, 384 - 423, 446 - 451, 518 - 542, 691 - 700
* Saved-news scrolls on 320 - 375
* https://prnt.sc/WwTIQ00GcW23

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Please add come sample saved cards on "home" page so that I can test the layout, since the search doesn't work yet.

- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/WKR9J7Z7M6rB Elements can't be used without their block. There are many similar cases in the project, please correct all of them

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* https://prnt.sc/F9Xk6ZSQaiak "ul" can't be a child of "ul". Each card should be a "li", inside one "ul"

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* https://prnt.sc/Em8Wwc4WmJUp

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover effect on a card bookmark from the mockup: https://prnt.sc/o7v7VfcnRLh8
* The bookmark on the card should have "marked" state implemented: https://prnt.sc/hvF3kmwz4XPe

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by moorek11c** [comment]
the search now works and App is responsive

**Comment by ImaliaNsk** [comment]
Amazing job, the project's almost perfect, and only a few points short from being accepted. Good luck with final corrections!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Saved-news scrolls on 518 - 542

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/BHzC2c93n6mx Elements can't be used without their block. There are many similar cases in the project, please correct all of them

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* https://prnt.sc/7V4DZ4nrYJqY ul is a list, li is a list item. li should be inside ul, not the other way around

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* The bookmark on the card should have "marked" state implemented: https://prnt.sc/hvF3kmwz4XPe

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by ImaliaNsk** [comment]
Perfect, the project is accepted, you did a great job with correcting your project! I wish you success in your future projects!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/BAFtLXAt7YKp Elements can't be used without their block. There are many similar cases in the project, please correct all of them

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* The bookmark on the card should have "marked" state implemented: https://prnt.sc/hvF3kmwz4XPe

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 92

**Comment by moorek11c** [comment]
Thank you so much it has been a journey.

**Pull request merged**
